server:
  port: 8484
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
auth:
  jwt-secret: "vr4567ujbvftyuikmnbresxcfreswert8y8uhbgyf32qsefg"
springdoc:
  api-docs:
    path: /api-docs